name: qcfb
channels:
    - conda-forge
    - pytorch
    - pyg
    - nvidia
dependencies:
    - python=3.7
    - pip
    - pip:
        - fedml
    - pytorch
    - pyg
    - mpi4py
    - wandb
    - ogb