common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "ogbg-molhiv"
  data_cache_dir: ~/fedgraphnn_data/
  partition_method: "hetero"
  partition_alpha: 0.1

model_args:
  model: "graphormer"
  hidden_size: 32
  node_embedding_dim: 32
  graph_embedding_dim: 64
  readout_hidden_dim: 64
  alpha: 0.2
  num_heads: 2
  dropout: 0.3
  normalize_features: False
  normalize_adjacency: False
  sparse_adjacency: False

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 1
  client_num_per_round: 1
  comm_round: 100
  epochs: 1
  batch_size: 64
  client_optimizer: adam
  learning_rate: 0.001
  weight_decay: 0.001
  metric: "aucroc"

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 1
  using_gpu: true
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: b2607f7743bc9b1cf3be074b9db485ff1b52663e
  wandb_project: fedml_test
  wandb_name: fedml_torch_sysml_bench