# You can define a cluster containing multiple GPUs within multiple machines by defining `gpu_mapping.yaml` as follows:

# config_cluster0:
#     hostname_node_0: [num_of_processes_on_GPU0, num_of_processes_on_GPU1, ..., num_of_processes_on_GPU_n]
#     hostname_node_1: [num_of_processes_on_GPU0, num_of_processes_on_GPU1, ..., num_of_processes_on_GPU_n]
#     hostname_node_m: [num_of_processes_on_GPU0, num_of_processes_on_GPU1, ..., num_of_processes_on_GPU_n]


mapping_default:
    jupyter-zminot3: [2]
