name: qcfb
channels:
    - pytorch
    - pyg
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - pytorch==1.12.1
    - torchvision==0.13.1
    - torchaudio==0.12.1
    - cudatoolkit==11.6
    - pip:
        - fedml
    - pyg
    - mpi4py
    - wandb
    - rdkit
    - ogb